name: SA-MP Persistent Runner

on:
  workflow_dispatch:
  push:
    paths:
      - .github/trigger.txt

jobs:
  run-server:
    runs-on: ubuntu-latest
    timeout-minutes: 330  # 5.5 hours

    concurrency:
      group: samp-server-loop
      cancel-in-progress: false

    env:
      PLAYIT_TOML: ${{ secrets.PLAYIT_TOML }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Start SA-MP server
        run: |
          chmod +x start.sh

          ./start.sh

      - name: Save server files and push to repo
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "actions@github.com"
          git add server/* || true
          if ! git diff --cached --quiet; then
            git commit -m "Auto-save server files at $(date)"
            git push
          fi

      - name: Trigger next run
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "actions@github.com"
          echo "Restart at $(date)" >> .github/trigger.txt
          git add .github/trigger.txt
          git commit -m "Auto-retrigger at $(date)"
          git push
